name: deploy to sonatype dev
on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        required: true
        description: デプロイするモジュール
        options:
        - playtest-db
        - playtest-gauge-db
        - playtest-browser
        - playtest-gauge-browser
        - playtest-gauge-rest
        - playtest-json

jobs:
  deploy_to_dev:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Gauge install
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          gauge install java --version 0.7.15
          gauge version
      - name: Start Database
        run: |
          cd  playtest-gauge-db/docker/db/postgresql/
          docker-compose up -d
      - name: Test & Deploy
        run: |
          for MVN_PROJ in playtest-gauge-browser playtest-browser playtest-db playtest-gauge-db playtest-gauge-rest playtest-json; do
            pushd $MVN_PROJ
            gauge config runner_connection_timeout 180000
            gauge config runner_request_timeout 180000
            mvn clean test deploy --batch-mode --no-transfer-progress -DperformRelease=true
            popd
          done
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
