name: Test for Pull Request & Merge branches

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

jobs:
  test_for_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup chromedriver
        run: |
          curl -sL -o chromedriver-linux64.zip  $(curl 'https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json' | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
      - name: Gauge install
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          gauge install java --version 0.7.15
          gauge install screenshot
          gauge install html-report
          gauge version
      - name: Start Database
        run: |
          cd playtest-gauge-db/docker/db/postgresql/
          docker compose up -d
      - name: Run test
        run: |
          gauge config runner_connection_timeout 180000
          gauge config runner_request_timeout 180000
          for MVN_PROJ in playtest-gauge-browser playtest-browser playtest-db playtest-gauge-db playtest-gauge-rest playtest-json
          do
            pushd $MVN_PROJ
            mvn test
            popd
          done
